import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/components/providers";
import { upsertStripeSubscriptionProducts } from "@/actions/stripe";
import { plans } from "@/utils/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await upsertStripeSubscriptionProducts(plans.map(plan => ({
    name: plan.title,
    price: plan.price,
  })));

  return (
    <html lang="en">
      <body id="AiChatBot" className={`${inter.className} h-screen`}>
        {children}
      </body>
    </html>
  );
}
